//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyArena.DeckAdvisor.Console.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DailyArena.DeckAdvisor.Console.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arena Standard.
        /// </summary>
        internal static string Item_ArenaStandard {
            get {
                return ResourceManager.GetString("Item_ArenaStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string Item_Ascending {
            get {
                return ResourceManager.GetString("Item_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booster Cost.
        /// </summary>
        internal static string Item_BoosterCost {
            get {
                return ResourceManager.GetString("Item_BoosterCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booster Cost (Ignoring Collection).
        /// </summary>
        internal static string Item_BoosterCostIgnoringCollection {
            get {
                return ResourceManager.GetString("Item_BoosterCostIgnoringCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booster Cost (Ignoring Wildcards).
        /// </summary>
        internal static string Item_BoosterCostIgnoringWildcards {
            get {
                return ResourceManager.GetString("Item_BoosterCostIgnoringWildcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brawl.
        /// </summary>
        internal static string Item_Brawl {
            get {
                return ResourceManager.GetString("Item_Brawl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Count.
        /// </summary>
        internal static string Item_CommonCount {
            get {
                return ResourceManager.GetString("Item_CommonCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck Score.
        /// </summary>
        internal static string Item_DeckScore {
            get {
                return ResourceManager.GetString("Item_DeckScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Item_Default {
            get {
                return ResourceManager.GetString("Item_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string Item_Descending {
            get {
                return ResourceManager.GetString("Item_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historic (Bo1).
        /// </summary>
        internal static string Item_Historic_Bo1 {
            get {
                return ResourceManager.GetString("Item_Historic_Bo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historic (Bo3).
        /// </summary>
        internal static string Item_Historic_Bo3 {
            get {
                return ResourceManager.GetString("Item_Historic_Bo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mythic Rare Count.
        /// </summary>
        internal static string Item_MythicRareCount {
            get {
                return ResourceManager.GetString("Item_MythicRareCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare Count.
        /// </summary>
        internal static string Item_RareCount {
            get {
                return ResourceManager.GetString("Item_RareCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string Item_Standard {
            get {
                return ResourceManager.GetString("Item_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncommon Count.
        /// </summary>
        internal static string Item_UncommonCount {
            get {
                return ResourceManager.GetString("Item_UncommonCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win/Loss Record.
        /// </summary>
        internal static string Item_WinRate {
            get {
                return ResourceManager.GetString("Item_WinRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading card database....
        /// </summary>
        internal static string Loading_LoadingCardDatabase {
            get {
                return ResourceManager.GetString("Loading_LoadingCardDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to exit..
        /// </summary>
        internal static string Message_PressToExit {
            get {
                return ResourceManager.GetString("Message_PressToExit", resourceCulture);
            }
        }
    }
}
